// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusRDM.Data.Context;

#nullable disable

namespace NexusRDM.Data.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260510120000_AddConnectionUsername")]
    partial class AddConnectionUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NexusRDM.Core.Models.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("NexusRDM.Core.Models.ConnectionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalSourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconGlyph")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RdpSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SshAuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshKeyFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshKeyPassphraseCredentialKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ExternalSourceId", "ExternalId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("NexusRDM.Core.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("NexusRDM.Core.Models.ProxmoxSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreTlsErrors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedCertThumbprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Realm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RootGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxSources");
                });

            modelBuilder.Entity("NexusRDM.Core.Models.ConnectionProfile", b =>
                {
                    b.HasOne("NexusRDM.Core.Models.ProxmoxSource", "ExternalSource")
                        .WithMany()
                        .HasForeignKey("ExternalSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexusRDM.Core.Models.Group", "Group")
                        .WithMany("Connections")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExternalSource");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NexusRDM.Core.Models.Group", b =>
                {
                    b.HasOne("NexusRDM.Core.Models.Group", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NexusRDM.Core.Models.Group", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
